version: "3.9"
services:
  api:
    image: ${DOCKER_REPO}:${DOCKER_TAG}
    init: true
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - API_URL
      - AWS_REGION
      - AWS_COGNITO_POOL_ID
      - AWS_COGNITO_CLIENT_ID